modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="time"
version="${mod_version}"
displayName="Time: Zero Hour Archives"
authors="lingmu"
description='''Temporal puzzle ruins, research and the Last Chronicler. Standalone NeoForge content module for Soul-Forge.'''
[[dependencies.time]]
modId="neoforge"
type="required"
versionRange="[21.1.233,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.time]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
